# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

# Specify your gem's dependencies in chef_yaml_to_json.gemspec
gemspec

group :development do
  gem 'rake'
  gem 'rdoc'
  gem 'yard'
end

group :test do
  gem 'cucumber'
  gem 'fivemat'
  gem 'aruba'
  gem 'rspec'
end
