---
driver:
  name: gce
  project: funky-penguin-12345
  zone: us-east1-c
  email: me@mycompany.com
  tags:
    - test-kitchen
  service_account_scopes:
    - devstorage.read_write
    - userinfo.email

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  username: chefuser
  ssh_key: /root/.ssh/learn-chef.pem

platforms:
  - name: centos-7
    driver:
      image_project: centos-cloud
      image_name: centos-7-v20170227

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
