# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

CHEF_SERVER_SCRIPT = <<EOF.freeze
# install chef server
echo "Installing Chef Server..."
apt-get update
apt-get -y install curl

# ensure the time is up to date
apt-get -y install ntp
service ntp stop
ntpdate -s time.nist.gov
service ntp start
if [ ! -f /downloads/chef-server-core_12.8.0_amd64.deb ]; then
  wget -P /downloads https://packages.chef.io/stable/ubuntu/14.04/chef-server-core_12.8.0-1_amd64.deb
fi
sudo dpkg -i /downloads/chef-server-core_12.8.0-1_amd64.deb
sudo chef-server-ctl reconfigure

# install chef manage
echo "Install Chef Manage"
# sudo chef-server-ctl install chef-manage
# sudo chef-server-ctl reconfigure
# sudo chef-manage-ctl reconfigure --accept-license

# restart services
sudo chef-server-ctl restart

# create admin user
echo "Creating users and organization..."
sudo chef-server-ctl user-create admin Bob Admin admin@4thcoffee.com insecurepassword --filename admin.pem
sudo chef-server-ctl org-create 4thcoffee "Fourth Coffee, Inc." --association_user admin --filename 4thcoffee-validator.pem

echo "Synchronizing admin and validator keys..."
mkdir -p /vagrant/secrets
cp -f /etc/opscode/webui_priv.pem /vagrant/secrets
cp -f /etc/opscode/pivotal.pem /vagrant/secrets
cp -f /home/vagrant/admin.pem /vagrant/secrets
cp -f /home/vagrant/4thcoffee-validator.pem /vagrant/secrets

# copy environment variables to share
#mkdir -p /vagrant/env/server
#cp /opt/opscode/sv/chef_gate/env/* /vagrant/env/server

echo "Your Chef server is ready!"
EOF

NODE_SCRIPT = <<EOF.freeze
echo "Preparing node..."
yum -y install ntp
systemctl start ntpd
systemctl enable ntpd

echo "10.1.1.33 chef-server.test" | tee -a /etc/hosts
EOF

def set_hostname(server)
  server.vm.provision 'shell', inline: "hostname #{server.vm.hostname}"
end

Vagrant.configure(2) do |config|

  config.vm.define 'chef-server' do |cs|
    cs.vm.box = 'bento/ubuntu-14.04'
    cs.vm.hostname = 'chef-server.test'
    cs.vm.network 'private_network', ip: '10.1.1.33'
    cs.vm.provision 'shell', inline: CHEF_SERVER_SCRIPT.dup
    set_hostname(cs)

    cs.vm.provider 'virtualbox' do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define 'node1' do |n|
    n.vm.box = 'bento/centos-7.2'
    n.vm.hostname = 'node1.test'
    n.vm.network 'private_network', ip: '10.1.1.34'
    n.vm.provision :shell, inline: NODE_SCRIPT.dup
    set_hostname(n)
  end

end
