---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[email::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      postfix:
        main:
          mydomain: 'example.com'
          myorigin: 'example.com'
